name = "PackageInABlink"
uuid = "29c12bd1-d721-479e-9f19-f3213c237221"
authors = ["Eben60"]
version = "0.1.0"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
StartupCustomizer = "fb0408be-4331-42cc-8584-db8fa022598a"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
